a note to migrate server
CAPU-ENG/CAPU-SA pull request #6
Opened 2016-12-14 06:24 UTC by QwertyJack

some useful note

2016-12-14 07:13 UTC, QwertyJack commented
@huxuan @JeldorPKU

2016-12-14 07:24 UTC, JeldorPKU commented
附议！

2016-12-14 09:05 UTC, QwertyJack commented
@huxuan

2016-12-14 09:31 UTC, huxuan commented
I will take a look soon.

2016-12-16 03:03 UTC, huxuan requested changes
All in all, it looks great. Just some minor issues commented, feel free to reach me in case of any problem.

2016-12-16 03:03 UTC, huxuan commented on migrat.md
> +sudo apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0
Do we really need php7.0?

2016-12-16 03:03 UTC, huxuan commented on migrat.md
> +   ServerName chexie.net
How about supporting `*.chexie.net` as well?

2016-12-16 03:03 UTC, huxuan commented on vhost.conf.example
> +	    <IfModule !mod_authz_core.c>
Better indentation.

2016-12-16 03:03 UTC, huxuan commented on migrat.md
> +2016年 12月 14日 星期三 11:14:48 CST
Suggest to use ISO 8601 format as here are the only Chinese characters.

[1] https://en.wikipedia.org/wiki/ISO_8601

2016-12-16 03:03 UTC, huxuan commented on migrat.md
> +mysql -uroot -p < foo.sql
I suggest we create a standalone mysql user for CAPUBBS for better security.

2016-12-16 03:03 UTC, huxuan commented on vhost.conf.example
> +
Redundant empty line.

2016-12-16 03:07 UTC, huxuan commented on .gitignore
> +/bin/conf
Why we need to ignore this file? as it's already exist.

2016-12-16 15:45 UTC, QwertyJack commented on migrat.md
> +2016年 12月 14日 星期三 11:14:48 CST
this line is not necessary at all

2016-12-16 15:45 UTC, QwertyJack commented on migrat.md
> +sudo apt-get install php7.0 php5.6 php5.6-mysql php-gettext php5.6-mbstring php-xdebug libapache2-mod-php5.6 libapache2-mod-php7.0
nope

2016-12-16 15:46 UTC, QwertyJack commented on migrat.md
> +mysql -uroot -p < foo.sql
just for data sync, only excutes once

2016-12-16 16:28 UTC, QwertyJack commented on .gitignore
> +/bin/conf
not secure; I would not have uploaded it; my fault.
How to purge it?

2016-12-16 16:28 UTC, QwertyJack commented on migrat.md
> +   ServerName chexie.net
i do not like that
see ["is-a-wildcard-dns-record-bad-practice"](http://serverfault.com/questions/483576/is-a-wildcard-dns-record-bad-practice)

2016-12-16 16:35 UTC, JeldorPKU commented on .gitignore
> +/bin/conf
@QwertyJack `git rm /bin/conf`
You have to manually delete it.

2016-12-18 07:00 UTC, huxuan approved these changes

2016-12-18 07:01 UTC, merged